sudo: required
dist: trusty
install:
  - npm install -g firebase-tools
script:
  - mkdir -p public
  - cp -R images index.html *.pdf public/
after_success:
  - firebase deploy --non-interactive --token $FIREBASE_TOKEN --project scalacontractors-5b130
cache:
  directories:
    - $HOME/.npm
env:
  secure: "bhvjhjTLMLekrz1iSHf2xsfY0ZdCVLUXJS6moa2K7HGexNzFUWIf3UCImOcWMtRs1cuXDOmldYTI2I72lHUEtbJDZCSu113nbkeoOMiAp0o2Knz9TvkfLLqUCfYbOdEM58EXj0MWXR1o7bFY6Zca4fkjxQdc6T1PBvLbshDikhlYOMvTDloVoL9uVDWjWOTppkLSYzgR8K+fys68wlSAg9xmawInKH5MzCUlQfZ612/Vs/DmhFfY06DG3hq5RDxHxEmMCwaBOAvbootOKDsp6YRv8oaaceGYV1InnU5kY9iAgEhjH/Q1c0qUcq7+4fnQzSP51R4/YQ2scH5MfjQYAL+InnZB5OIufWm6RSgf6E8i9A2g4tfGS9aWyKCx0HVaEunWpoPQ4GqA0bEmd5F0Yw45hqq02xsR8IQtx9qSKJJVe9BC2snPrut3V2xn43ebqwZuGaxkwnQS0I0G7UkyG0rscjEum3nW0wo03MHeU1s1CgaOhZS0957Wq1uXnD2QT0AORe0IA0xAIH8/9BbyJZxrTqFrgci2/Kea8s5pRHvoW+aaCYLi9ZB3jHRfkG71DZuVSY25BilBdhUQHQJ5cIrYle2azazWNYE/QmNQUJLmUCrfe2GGSJHXybegxVt0T/hrxXQ2+gaMuQUCzELABVk+o72T+7mOHWvKli4uLZY="
